### ISSUE TITLE
Yes BUt CaN iT rUn DoOm ?

### ISSUE THREAD

**Issue by toxicbloud** [Paulux06/AlgoSnipper#1]
hello i found your extension but i wonder why i can't play doom with it

**Comment by Paulux06** [comment]
I'm NoT tAlEnTeD eNoUgH iNfOrTuNaTeLy ... (nn en vrai je vais essayer la
prochaine fois)

**Comment by toxicbloud** [comment]
I SeE ThAt I cAn PlAy DoOm NoW ThX !
